apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-generator
  namespace: argocd
spec:
  project: default
  source:
    chart: kubernetes-secret-generator
    repoURL: https://helm.mittwald.de
    targetRevision: 3.4.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: secret-generator
