apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: argocd-frontend-config
    networking.gke.io/managed-certificates: argocd-tls-cert
    external-dns.alpha.kubernetes.io/hostname: argocd.k8s.broncoctf.xyz
    ingressClassName: "gce"
  labels:
    name: argocd
spec:
  rules:
    - host: argocd.k8s.broncoctf.xyz
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: argocd-server
              port:
                number: 80
