apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- ./frontendconfig-argocd-frontend-config.yaml
- ./ingress-argocd.yaml
- ./managedcertificate-argocd-tls-cert.yaml

patches:
- path: ./service-argocd-server-patch.yaml
- path: ./configmap-patch.yaml
