apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctfd
  namespace: ctfd
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: ctfd-frontend-config
    networking.gke.io/managed-certificates: ctfd-tls-cert
    kubernetes.io/ingress.class: "gce"
    external-dns.alpha.kubernetes.io/hostname: www.broncoctf.xyz, broncoctf.xyz
  labels:
    name: ctfd
spec:
  defaultBackend:
    service:
      name: ctfd
      port:
        number: 80