apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ctfd
  labels:
    ctfd: ctf-pv
    app: ctfd-pv-uploads
  name: ctfd-pv-uploads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi