apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ctfd
  labels:
    ctfd: mysql-pv
    app: ctfd-mysql-db-pv
  name: ctfd-mysql-db-pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi