apiVersion: v1
kind: Secret
metadata:
  name: ctfd-mysql-passwords
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password,root_password
    secret-generator.v1.mittwald.de/encoding: base64url