apiVersion: v1
kind: Service
metadata:
  namespace: ctfd
  labels:
    app: ctfd-mysql-db
  name: ctfd-mysql-db
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: ctfd-mysql-db
  type: ClusterIP