apiVersion: v1
kind: Service
metadata:
  namespace: ctfd
  labels:
    app: ctfd-redis-cache
  name: ctfd-redis-cache
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: ctfd-redis-cache
  type: ClusterIP