apiVersion: v1
kind: Service
metadata:
  name: nc-chals
  annotations:
    external-dns.alpha.kubernetes.io/hostname: serpant.broncoctf.xyz
spec:
  selector:
    app: nc-chals
  ports:
  - name: serpant
    protocol: TCP
    port: 8000
    targetPort: serpant-nc
  type: LoadBalancer
